{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ .Values.imagePullSecret.dockerconfigjson | indent 4 }}
{{- end }}