apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
{{ .Values.imagePullSecrets.dockerconfigjson | indent 4 }}