apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson
stringData:
  # Замените значение ниже на содержимое вашего ~/.docker/config.json
  # после логина в ghcr.io. Kubernetes сам закодирует строку как secret.
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "auth": "REPLACE_WITH_BASE64_LOGIN_TOKEN"
        }
      }
    }
